version: "3.9"

services:
  pgdatabase:
    image: postgres:16
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      SCRIPT_NAME: /pgadmin4
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_COOKIE_DEFAULT_SECURE: "False"
      PGADMIN_CONFIG_COOKIE_SAMESITE: "Lax"
 
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"
    networks:
      - pg-network
    depends_on:
      - pgdatabase
    restart: unless-stopped

volumes:
  ny_taxi_postgres_data:
  pgadmin_data:

networks:
  pg-network:
    driver: bridge
